authorName: default
experimentName: example_pytorch_cifar10
trialConcurrency: 1
maxExecDuration: 100h
maxTrialNum: 60
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: Random
  # classArgs:
  #   #choice: maximize, minimize
  #   #optimize_mode: maximize
  gpuIndices: '0'

trial:
  command: python3 main.py
  codeDir: .
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu:  1
  useActiveGpu: true
