authorName: default
experimentName: simple_experiment_2d
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 50
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
# NNI custom tuner configuration
tuner:
  # Set path to Tuun
  codeDir: /home/ubuntu/proj/tuun/tuun
  classFileName: nni_tuner.py
  className: TuunTuner
  # Any parameter need to pass to your tuner class __init__ constructor
  # can be specified in this optional classArgs field, for example
  classArgs:
    #choice: minimize, maximize
    optimize_mode: minimize
    tuun_config: {
        'backend': 'probo',
        'acqfunction_config': {'name': 'default', 'acq_str': 'ucb'},
    } 
trial:
  command: python trial.py
  codeDir: .
  gpuNum: 0
