authorName: default
experimentName: stan_experiment_3d
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 50
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
#tuner:
  ##choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  ##SMAC (SMAC should be installed through nnictl)
  #builtinTunerName: TPE
  #classArgs:
    ##choice: maximize, minimize
    #optimize_mode: maximize
tuner:
  codeDir: /home/ubuntu/proj/tuun-dev/tuun
  classFileName: nni_tuner.py
  className: TuunTuner
  # Any parameter need to pass to your tuner class __init__ constructor
  # can be specified in this optional classArgs field, for example
  classArgs:
    tuun_config: {
        'model_config': {'name': 'standistmatgp'},
        'acqfunction_config': {'name': 'default', 'acq_str': 'ucb'},
    } 
trial:
  command: python trial.py
  codeDir: .
  gpuNum: 0
